bar:
  height: 30
  location: top
  spacing: 10
  margin: 7
  background: 000000ff

  right:
    - network:
        name: wlp1s0f0
        poll-interval: 1000
        content:
          map:
            conditions:
              state == down:
                - string: {text: "offline", font: "style=solid:size=24", foreground: "bc5653ff"}
              state == up:
                - string: {text: "{ssid}", font: "style=solid:size=24"}
    - battery:
        name: macsmc-battery
        poll-interval: 30000
        content:
          map:
            conditions:
              state == unknown:
                - string: {text: "{capacity}%", font: "style=solid:size=24"}
              state == discharging:
                - string: {text: "{capacity}%", font: "style=solid:size=24"}
              state == charging:
                - string: {text: "⌁", font: "style=solid:size=24", foreground: "909d63ff"}
                - string: {text: "{capacity}%", font: "style=solid:size=24", foreground: "909d63ff"}
              state == full:
                - string: {text: "{capacity}%}", font: "style=solid:size=24"}
    - clock:
        content:
          - string: {text: "{date}", font: "style=solid:size=24"}
          - string: {text: " ",      font: "style=solid:size=24"}
          - string: {text: "{time}", font: "style=solid:size=24"}
          - string: {text: " ",      font: "style=solid:size=24"}
