bar:
  height: 30
  location: top
  spacing: 10
  margin: 7
  background: 000000ff

  right:
    - network:
      poll-interval: 1000
      content:
        map:
          default: {empty: {}}
          conditions:
            name == wlp1s0f0:
              map:
                default: {string: {text: "default",}}
                conditions:
                  state == down: {string: {text: "⌀"}}
                  state == up:
                    map:
                      default:
                        - string: {text: "፨"}
                        - string: {text: "{ssid} {dl-speed:mb}/{ul-speed:mb} Mb/s"}

                          conditions:
                            ipv4 == "":
                              - string: {text: "ipv4"}
                              - string: {text: "{ssid} {dl-speed:mb}/{ul-speed:mb} Mb/s"}
    - battery:
      name: macsmc-battery
      poll-interval: 30000
      content:
        map:
          conditions:
            state == unknown:
              - string: {text: "{capacity}%", font: "style=solid:size=24"}
            state == discharging:
              - string: {text: "{capacity}%", font: "style=solid:size=24"}
            state == charging:
              - string: {text: "⌁", font: "style=solid:size=24", foreground: "909d63ff"}
              - string: {text: "{capacity}%", font: "style=solid:size=24", foreground: "909d63ff"}
            state == full:
              - string: {text: "{capacity}%}", font: "style=solid:size=24"}
    - clock:
      content:
        - string: {text: "{date}", font: "style=solid:size=24"}
        - string: {text: " ",      font: "style=solid:size=24"}
        - string: {text: "{time}", font: "style=solid:size=24"}
        - string: {text: " ",      font: "style=solid:size=24"}

